package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"strings"

	lifecodex "life_tools/internal/life_codex"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "enroll":
		runEnroll(os.Args[2:])
	case "serve":
		runServe(os.Args[2:])
	default:
		usage()
		os.Exit(2)
	}
}

func runEnroll(args []string) {
	flags := flag.NewFlagSet("enroll", flag.ExitOnError)
	configPath := flags.String("config", lifecodex.DefaultAgentConfigPath, "agent config path")
	serverURL := flags.String("server", "", "life_codex_server URL")
	token := flags.String("token", "", "enrollment token generated by server")
	name := flags.String("name", "", "machine name")
	roots := flags.String("roots", "", "comma-separated allowed roots")
	codexPath := flags.String("codex-path", "", "codex executable path")
	attachmentDir := flags.String("attachment-dir", "", "attachment directory")
	maxActive := flags.Int("max-active-sessions", 0, "max concurrent sessions")
	pollSeconds := flags.Int("poll-seconds", 0, "poll interval seconds")
	flags.Parse(args)

	if *token == "" {
		log.Fatal("--token is required")
	}
	config := loadAgentConfigLoose(*configPath)
	if *serverURL != "" {
		config.ServerURL = *serverURL
	}
	if *name != "" {
		config.MachineName = *name
	}
	if *roots != "" {
		config.AllowedRoots = splitCSV(*roots)
	}
	if *codexPath != "" {
		config.CodexPath = *codexPath
	}
	if *attachmentDir != "" {
		config.AttachmentDir = *attachmentDir
	}
	if *maxActive > 0 {
		config.MaxActiveSessions = *maxActive
	}
	if *pollSeconds > 0 {
		config.PollSeconds = *pollSeconds
	}
	if config.MachineName == "" {
		host, _ := os.Hostname()
		config.MachineName = host
	}
	if len(config.AllowedRoots) == 0 {
		log.Fatal("--roots is required")
	}
	resp, err := lifecodex.EnrollAgent(context.Background(), *configPath, config, *token)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("enrolled machine %s\n", resp.MachineID)
}

func runServe(args []string) {
	flags := flag.NewFlagSet("serve", flag.ExitOnError)
	configPath := flags.String("config", lifecodex.DefaultAgentConfigPath, "agent config path")
	flags.Parse(args)
	config, err := lifecodex.LoadAgentConfig(*configPath)
	if err != nil {
		log.Fatal(err)
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	if err := lifecodex.RunAgent(ctx, config); err != nil && ctx.Err() == nil {
		log.Fatal(err)
	}
}

func loadAgentConfigLoose(path string) lifecodex.AgentConfig {
	config, err := lifecodex.LoadAgentConfig(path)
	if err == nil {
		return config
	}
	if path != "" && os.IsNotExist(err) {
		return lifecodex.DefaultAgentConfig()
	}
	log.Fatal(err)
	return lifecodex.AgentConfig{}
}

func splitCSV(value string) []string {
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

func usage() {
	fmt.Fprintf(os.Stderr, `Usage:
  life_codex_agent enroll --server URL --token TOKEN --roots ROOT[,ROOT] [options]
  life_codex_agent serve --config PATH
`)
}
